---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE}
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    command: '/sbin/init --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml'
    exposed_ports:
      - 9100/tcp
      - 9090/tcp
    privileged: True
    published_ports:
      - 0.0.0.0:9100:9100/tcp
      - 0.0.0.0:9090:9090/tcp
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
